# Generated by Django 5.1.1 on 2024-10-11 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=100, verbose_name='Pet Details')),
                ('imagepath', models.ImageField(default='', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('petid', models.ForeignKey(db_column='petid', on_delete=django.db.models.deletion.CASCADE, to='petapp.pet')),
            ],
        ),
    ]
