# Generated by Django 5.1.1 on 2024-10-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='quantity',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uid',
            new_name='id',
        ),
    ]
